version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      - meilisearch
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    command: ["meilisearch", "--db-path", "/meili_data"]

volumes:
  db_data: 